### ISSUE TITLE
OSX El Capitan Unsupported

### ISSUE THREAD

**Issue by weems** [Benjamin-Dobell/Heimdall#317] opened 2015-12-10 00:04 UTC
Please expand the .dmg / .pkg to function on OSX 10.11.1 -- El Capitan. Thanks

**Comment by matgessel** [comment] 2015-12-13 02:25
Duplicate of #291?

**Comment by kevinpapst** [comment] 2015-12-27 10:24
Here is a shorthand version of the closed issue #291, try this file: 
https://bitbucket.org/benjamin_dobell/heimdall/downloads/Heimdall-1.4.1-Unofficial-Signed.dmg

**Comment by bunnyfu** [comment] 2016-01-05 14:12
Kevinpapst, thanks a ton. Was also having problems building from source on OS X El Capitan.

**Comment by Silvercast** [comment] 2016-03-02 15:14
thanks

**Comment by Benjamin-Dobell** [comment] 2016-05-20 11:04
https://github.com/Benjamin-Dobell/Heimdall/issues/291

**Closed by Benjamin-Dobell** 2016-05-20 11:04 UTC
